### PR TITLE
For mac M2+ user

### PR DESCRIPTION
**Pull request by Fangchi-0621**
Added the instruction to compile the binary file compatible to Mac M2 and onwards.

### CODE REVIEW

**Review by WeirongChen — APPROVED** [review]

**Review by WeirongChen — APPROVED** [review]

**Comment by WeirongChen** [comment]
Thank you for adding the instruction of compiling snake for mac M2+ users.

**Comment by samgregory** [comment]
Hi @Fangchi-0621 and @WeirongChen 

I installed DeepEdge on a Mac today. I ran into two issues with SLURP that weren't covered in your installation notes. I thought you might want to update your readMe file:

Problem 1 -  The SLURP executable will need verification to be run 

Steps: Locate the file in the DeepMake folder). Right click, select Open and Open (agreeing to the security warning "macOS cannot verify the developer of “make_snake.mexmaci64”. Are you sure you want to open it?”)

Problem 2 - SLURP Problem will make calls to the GNU scientific library (hard coded to version 1.9). This wasn't listed in your requirements section.

Steps: Installation of GSL on a Mac is very easy if you've got Homebrew. Open a terminal window. Type the command: **brew install gsl** Create a symlink: **ln -s /usr/local/lib/libgsl.dylib /usr/local/lib/libgsl.19.dylib**

**Comment by WeirongChen** [comment]
Hi @samgregory, 
Thank you for the feedback and your solution!
I will test it and update the readme file when I have some time on it.

**Comment by Fangchi-0621** [comment]
學長您好：

我是葉芳綺，現在是謝豐帆老師實驗室的學生。我也有收到信！

P1:  因為是在我的電腦(M3 pro)上面生成的binary file所以我好像不用那個verification
所以沒有寫到很不好意思，不過照理說他是binary
file應該不用我們打開來讀取，因此應該只是要找個方法讓電腦可以接受這個從網路上下載來要跑的檔案對嗎？

P2: 我的電腦還沒有用過 brew外裝過任何東西，所以我在想是不是以前版本的mac還是什麼預設上不太一樣。


芳綺 敬上

**Pull request merged**
